### ISSUE TITLE
Cannot start Heroku Server

### ISSUE THREAD

**Issue by PolygonGraphics** [ottomated/CrewLink-server#121]
Error Code:

2020-12-28T20:24:54.900870+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=crewlink-69.herokuapp.com request_id=002fcac0-8e71-47af-a8e0-b1a10125c841 fwd="85.220.167.178" dyno= connect= service= status=503 bytes= protocol=https

Thank You!

**Comment by PlatinPython** [comment]
You still need to specify the **ADDRESS** variable.
Just simply go to _Settings>Config Vars_ and add a new variable with the **KEY** = **ADDRESS** and **VALUE** equal to the domain of your app.

**Comment by jmont-dev** [comment]
The following is reported by the heroku logs:

`_2020-12-28T23:20:04.238120+00:00__ app[web.1]: 2020-12-28T23:20:04+0000 <error> You must set the ADDRESS environment variable.`

This is likely a consequence of 274560a, which changed lines 50-54 of index.ts to include the following:

`if (!address) {
	logger.error('You must set the ADDRESS environment variable.');
	process.exit(1);
}`

It also removed a default address setting on line 154 that was previously included:

`	if (!address)
		address = http://${await publicIp.v4()}:${port};`

As PlatinPython has stated, you can add a Config Var in Heroku with the ADDRESS key and your app name to resolve this. However, it may make sense for the devs to include a default address setting for ease of deployment since many people using this tool are not technically inclined. From their perspective, they hit "Deploy to Heroku" and then simply see a crash screen for this version of the server. Unless they are knowledgeable enough to check the logs and understand how to set this environment variable, it may be a source of confusion for them.

One option is to simply call `let address = process.env.ADDRESS;` to give priority to a manually specified address, and then fall back on `address = http://${await publicIp.v4()}:${port};` if this is not properly set. This would allow configuration while still permitting the heroku deployment to work with a single click like it did previously.

Thanks again for your great work in making this mod.
