### ISSUE TITLE
"Error: Please Launch The Game On Steam"

### ISSUE THREAD

**Issue by Ghost942** [ottomated/CrewLink-server#24]
-Installed Crewlink
-Clicked "Launch Game"
-Get thrown error
-Think: Game installed on drive where Crewlink is not
-Think: Install game on same drive as Crewlink (C:)
-Un/reinstall game on C:
-Launch Crewlink
-Same error thrown

Game was bought legit through Steam
Any help on this is appreciated
![Screenshot 2020-12-06 130402](https://user-images.githubusercontent.com/43941387/101289925-0a8c8b80-37c5-11eb-95f1-8e48eb5a9bbb.png)

**Comment by adrian200223** [comment]
It doesn't have anything to do with the drive you have the game installed on. I have among us on F: and CrewLink on C:. You may have a problem.

I have looked through the code. It checks where you have installed Steam, say C:\Program Files (x86)\Steam, for example. There it runs steam.exe with the following parameters: -applaunch (open game) 945360 (among us identifier in steam). You can try it in cmd (search what it is on google): 

```
cd C:\Program Files (x86)\Steam
steam.exe -applaunch 945360
```
It will probably give you an error, because that's why you are here. Check that error online.

Also, this game does not need to launch the game, it detects the game running. Therefore, if you can go to the steam app and click to run the game there, it would have the same effect.

Good luck

**Comment by Ghost942** [comment]
Running CMD with the path to Steam (Y:\Program Files (x86)\Steam) and the command to launch the app was successful.

Steam is installed on Y: for the purpose of if something happens to the OS (as it has before), and thus I have Y: set as my dedicated HDD for all games, save 1 for a partition on my SSD. I digress.
I still receive the same error when launching CrewLink to then launch Among Us, even with running as Admin (as found in another issue)
It should be worth mentioning that Steam runs in Admin mode to bypass a download that breaks and freezes Steam.

Edit: Game launches with running CrewLink in Admin AND launching the game when it first appears, as opposed to moving the app to another monitor and attempting to launch

Closing ticket
