### ISSUE TITLE
2020.11.17 gameCode offset

### ISSUE THREAD

**Issue by badhex** [ottomated/CrewLink-server#3]
https://github.com/ottomated/CrewLink-server/blob/351fbd87ffc4ca778a6460d44aec9b6346eb3ef1/offsets/2020.11.17.yml#L12
Looks like the 2020.11.17.yml gameCode offset is incorrect. Client UI sits at MENU when you join games and doesn't change state. 

Checked via gamecheat and I get garbage from that pointer offset.

**Comment by ryantheleach** [comment]
I've been testing this all afternoon (Solo), it's probably due to the among us patch that released again without changing the version numbers. gameCode appears to be working correctly to me, as is all the state tracking.

I havn't been able to test with other players though, so it's possible that the offsets regarding player network id's or something is messed up.

See here for details on how to clear the cached values, and use the ones that released ~ 10 hours ago: https://github.com/ottomated/CrewLink/issues/19

**Comment by badhex** [comment]
That did it for me. Thanks!
