### ISSUE TITLE
Running the server off nginx causes real IP to be shown on the webpage.

### ISSUE THREAD

**Issue by RDalcolmo** [ottomated/CrewLink-server#40]
Hi guys. I run a Docker Cluster on nginx with a reverse proxy.

Currently I am hosting my own voice server at https://exampleurl.com which goes through a reverse proxy on port 80. However when users click inside the url the page displays the real IP:PORT url

![image](https://user-images.githubusercontent.com/9065913/101528254-127f3380-395d-11eb-8b12-a9d6c3e7616c.png)

Users won't be able to use that, they need to use the https://exampleurl.com . This often leads to confusion. Is there a way I can set the URL in the page to appear correctly and show the exampleurl.com

**Comment by Lermatroid** [comment]
There are ways that this can be fixed in a PR but if you want to fix it on your server, the easiest way would be to just go to the /views/index.pug file and modify the line where it says

`p This is a CrewLink Server running on #{address}.`

with

`p This is a CrewLink Server running on YOUR_URL_HERE.`

**Comment by RDalcolmo** [comment]
This solved it. Thanks!
